### ISSUE TITLE
[Marker.io] Stuck on purchase (Transaction still approved)

### ISSUE THREAD

**Issue by ReFiProtocol** [ReFi-Protocol/dashboard#51]
[![Screenshot_2024-08-29_08-51-46.png](https://mrkr.io/s/66d036a2320ff899472e3776/2)](https://mrkr.io/s/66d036a2320ff899472e3776/0)

Wallet public address:

Steps to reproduce: Buying pCRBN NFT on mobile (android) using built in phantom wallet browser. The UI will keep loading forever.

Actual result:

Expected result:

---

**Reported by:** CapyRefi (capyrefiprotocol@gmail.com) - [Contact via Marker.io](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1&comments=1)

**Source URL:** [https://beta.refiprotocol.io/marketplace](https://beta.refiprotocol.io/marketplace)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1)

**Console:** [⚠️  1 warning ](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>tablet</td></tr><tr><td><strong>Browser</strong></td><td>Android Browser 4.0</td></tr><tr><td><strong>Screen Size</strong></td><td>418 x 976</td></tr><tr><td><strong>OS</strong></td><td>Android 12.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>448 x 847</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2.625x</td></tr></table>

**Comment by QuimbyJr** [comment]
Hello @ReFiProtocol 
Have you been able to resolve this issue?

**Comment by ReFiProtocol** [comment]
yes

**Comment by ReFiProtocol** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66d036a2320ff899472e3779?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
